import os

TEMPLATE = """\
# LeetCode Practice

My LeetCode log. All solutions are in the `solutions/dayX/` folders.
My LinkedIn profile: [LinkedIn](https://leetcode.com/u/shreyanshVIT23/).

## **Note: This file is auto-generated.**
## **It is generated by `generate_readme.py`.**

{body}
"""


def parse_metadata(path):
    title = url = None
    with open(path, 'r') as f:
        for line in f:
            if line.startswith('# Title:'):
                title = line.partition(':')[2].strip()
            elif line.startswith('# URL:'):
                url = line.partition(':')[2].strip()
            if title and url:
                break
    return title, url


def main():
    days = sorted(d for d in os.listdir('solutions') if d.startswith('day'))
    md_body = []
    for day in days:
        md_body.append(f"## {day.capitalize()}\n")
        sol_dir = os.path.join('solutions', day)
        files = sorted(f for f in os.listdir(sol_dir) if f.endswith('.py'))
        for fn in files:
            path = os.path.join(sol_dir, fn)
            title, url = parse_metadata(path)
            num = fn.split('_')[0]
            if title and url:
                md_body.append(
                    f"- **{num}. [{title}]({url})** ([code]({path.replace(os.sep, '/')}))\n")
        md_body.append('\n')
    full = TEMPLATE.format(body=''.join(md_body))
    with open('README.md', 'w') as f:
        f.write(full)


if __name__ == '__main__':
    main()
