name: Update README

on:
  push:
    paths:
      - "solutions/**"

jobs:
  regen:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: true

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Run generator script
        run: python generate_readme.py

      - name: Commit & push README
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git diff --cached --quiet || (git commit -m "chore: auto-update README" && git push)

